config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  
  resources :employees do
    post :import_from_api, on: :collection
  end

  root 'employees#index'
  
  namespace :api do
    namespace :v1 do
      resources :employees
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/employee.rb
class Employee < ApplicationRecord
 
  validates :first_name, :last_name, :email, :department, :salary, presence: true
  validates :email, uniqueness: true

  scope :filtered, ->(department, min_salary, max_salary) {
    employees = all
    employees = employees.where(department: department) if department.present?
    employees = employees.where('salary >= ?', min_salary) if min_salary.present?
    employees = employees.where('salary <= ?', max_salary) if max_salary.present?
    employees
  }

  def self.all_departments
    pluck(:department).uniq.sort
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/v1/employees_controller.rb
module Api
  module V1
    class EmployeesController < ApplicationController
      def index
        employees = []
        10.times do
          employee = {
            first_name: Faker::Name.first_name,
            last_name: Faker::Name.last_name,
            email: Faker::Internet.email,
            department: Faker::Company.profession,
            salary: Faker::Number.between(from: 30000, to: 100000)
          }
          employees << employee
        end
        render json: employees
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :authenticate_user!, except: [:import_from_api]
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  def index
    @employees = Employee.filtered(params[:department], params[:min_salary], params[:max_salary])

    respond_to do |format|
      format.html
    end
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      redirect_to @employee, notice: 'Employee was successfully created.'
    else
      render :new
    end
  end

  def update
    if @employee.update(employee_params)
      redirect_to @employee, notice: 'Employee was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @employee.destroy
    redirect_to employees_path, notice: 'Employee was successfully destroyed.'
  end

  def import_from_api
    EmployeeDataImportWorker.perform_async
    redirect_to employees_path, notice: 'Importing employees data.'
  end

  private

  def set_employee
    @employee = Employee.find(params[:id])
  end

  def employee_params
    params.require(:employee).permit(:first_name, :last_name, :email, :department, :salary)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/employees/_employees_list.html.erb
<table class="table-size">
  <thead>
    <tr>
      <th>First Name(<%= @employees.count%>)</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Department</th>
      <th>Salary</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.first_name %></td>
        <td><%= employee.last_name %></td>
        <td><%= employee.email %></td>
        <td><%= employee.department %></td>
        <td><%= employee.salary %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= button_to 'Destroy', employee, method: :delete,  onclick: "return confirm('Are you sure?');"  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/employees/_form.html.erb
<div class="table-size">
  <%= form_with(model: employee, local: true) do |form| %>
    <% if employee.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

        <ul>
          <% employee.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :first_name %>
      <%= form.text_field :first_name %>
    </div>

    <div class="field">
      <%= form.label :last_name %>
      <%= form.text_field :last_name %>
    </div>

    <div class="field">
      <%= form.label :email %>
      <%= form.text_field :email %>
    </div>

    <div class="field">
      <%= form.label :department %>
      <%= form.text_field :department %>
    </div>

    <div class="field">
      <%= form.label :salary %>
      <%= form.text_field :salary %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/employees/edit.html.erb
<h1>Edit Employee</h1>

<%= render 'form', employee: @employee %>

<div class="actions">
  <%= link_to 'Show', @employee %>
  <%= link_to 'Back', employees_path %>
</div>

app/views/employees/index.html.erb
<h1 class="header1">Employees</h1>

<div class="button-container">
  <%= form_tag(import_from_api_employees_path, method: :post) do %>
    <%= button_tag 'Import Data from API', class: 'btn btn-primary' %>
  <% end %>
  <%= button_to "New Employee", new_employee_path,method: :get, class: "btn btn-primary" %>
</div>

<div class="search-form" style="">
  <div style="display: inline-block;">
    <%= form_tag employees_path, method: :get, remote: true, id: 'filter-form' do %>
      <div class="form-group">
        <%= label_tag :department, "Department" %>
        <%= select_tag :department, options_for_select(Employee.all_departments, params[:department]), { class: 'form-control', include_blank: 'Select Department' } %>
      </div>
      <div class="form-group">
        <%= label_tag :min_salary, "Min Salary" %>
        <%= number_field_tag :min_salary, params[:min_salary], class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= label_tag :max_salary, "Max Salary" %>
        <%= number_field_tag :max_salary, params[:max_salary], class: 'form-control' %>
      </div>
      <%= submit_tag "Filter", class: 'btn btn-primary' %>
    <% end %>
  </div>
  <div style="display: inline-block; vertical-align: top;">
    <%= button_to "Reset", employees_path, method: :get, params: {}, form: { id: 'filter-form' }, class: 'btn btn-secondary' %>
  </div>
</div>

<div id="employees-list">
  <%= render 'employees_list' %>
</div>

<script>
  $(document).ready(function() {
    $('#filter-form').submit(function(event) {
      event.preventDefault();
      const formData = $(this).serialize();
      const url = $(this).attr('action');

      $.ajax({
        url: url,
        method: 'GET',
        data: formData,
        dataType: 'html',
        beforeSend: function(xhr) {
          xhr.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
        },
        success: function(response) {
          $('#employees-list').html(response);
        },
        error: function(xhr, status, error) {
          console.error('AJAX Error:', error);
        }
      });
    });
  });
</script>

app/views/employees/new.html.erb
<h1 class="header1">New Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Back', employees_path, class: 'actions' %>

app/views/employees/show.html.erb
<div class="employee-details">
  <h1><%= @employee.first_name %> <%= @employee.last_name %></h1>
  
  <p><strong>Email:</strong> <%= @employee.email %></p>
  <p><strong>Department:</strong> <%= @employee.department %></p>
  <p><strong>Salary:</strong> <%= @employee.salary %></p>
</div>

<div class="actions">
  <%= link_to 'Edit', edit_employee_path(@employee) %>
  <%= link_to 'Back', employees_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmployeeManagementSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>
    
  <body>
    <div id="flash-messages">
      <% flash.each do |type, message| %>
        <div class="notice notice-<%= type %>">
          <p class="notice"><%= notice %> <%= alert %></p>
        </div>
      <% end %>
    </div>
    <% if user_signed_in? %>
      <div class="sign-out-container">
        <% if user_signed_in? %>
          <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "sign-out-btn" %>
        <% end %>
      </div>  
    <% end %>
    <%= yield %>
  </body>
</html>